tempo:
  tempo:
    metricsGenerator:
      # -- If true, enables Tempo's metrics generator (https://grafana.com/docs/tempo/next/metrics-generator/)
      enabled: true
  tempoQuery:
    # -- if False the tempo-query container is not deployed
    enabled: true
  serviceMonitor:
    enabled: true
