{{- if .Values.datasources.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-datavolume-permission
rules:
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["*"]
{{- range $sources := .Values.datasources.clientnamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-to-clientnamespace-sa-default-{{ $sources }}
  namespace: kubevirt
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $sources }}
roleRef:
  kind: ClusterRole
  name: kubevirt-datavolume-permission
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
