# https://github.com/kubernetes/website/blob/70a8ccdf821c90b7258519b92264740aeb48d02f/content/en/docs/tutorials/security/seccomp.md?plain=1#L130
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: "./profiles"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
