# https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/c02c72deeebe81ae44cc00d9b931043f30455b82/tests/BasicTestMountSPC.yaml
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: basic-test-mount-spc
spec:
  provider: aws
  secretObjects:
  - secretName: secret
    type: Opaque
    data:
    - objectName: SecretsManagerSync
      key: username
  - secretName: json-ssm
    type: Opaque
    data:
    - objectName: ssmUsername
      key: username
    - objectName: ssmPassword
      key: password
  - secretName: secrets-manager-json
    type: Opaque
    data:
    - objectName: secretsManagerUsername
      key: username
    - objectName: secretsManagerPassword
      key: password

  parameters:
    objects: |
        - objectName: "ParameterStoreTest1"
          objectType: "ssmparameter"
        - objectName: "ParameterStoreTestWithLongName"
          objectAlias: "ParameterStoreTest2"
          objectType: "ssmparameter"
        - objectName: "ParameterStoreRotationTest"
          objectType: "ssmparameter"
        - objectName: "SecretsManagerRotationTest"
          objectType: "secretsmanager"
        - objectName: "SecretsManagerTest1"
          objectType: "secretsmanager"
        - objectName: arn:aws:secretsmanager:${REGION}:${ACCOUNT_NUMBER}:secret:SecretsManagerTest2
          objectAlias: "SecretsManagerTest2"
        - objectName: "SecretsManagerSync"
          objectType: "secretsmanager"
        - objectName: "jsonSsm"
          objectType: "ssmparameter"
          jmesPath:
              - Path: "username"
                ObjectAlias: "ssmUsername"
              - Path: "password"
                ObjectAlias: "ssmPassword"
        - objectName: "secretsManagerJson"
          objectType: "secretsmanager"
          jmesPath:
              - Path: "username"
                ObjectAlias: "secretsManagerUsername"
              - Path: "password"
                ObjectAlias: "secretsManagerPassword"
---
kind: Pod
apiVersion: v1
metadata:
  name: basic-test-mount
spec:
  serviceAccountName: basic-test-mount-sa
  containers:
  - image: k8s.gcr.io/e2e-test-images/busybox:1.29
    name: busybox
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sleep"
    - "10000"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "basic-test-mount-spc"
