# https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/16
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-env
spec:
  provider: aws
  secretObjects:
    - secretName: secretdocker
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: "docker_config"
          key: .dockerconfigjson
  parameters:
    objects: |
      - objectName: "/secret/docker_config"
        objectType: "ssmparameter"
        objectAlias: "docker_config"
---
kind: Pod
apiVersion: v1
metadata:
  name: env-example
spec:
  serviceAccountName: sa-k8s-secret-poc
  imagePullSecrets:
    - name: secretdocker
  containers:
    - image: miki79/testimage:1
      name: testimage
      imagePullPolicy: Always
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets-env"
---
# example 2
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: docker-hub
spec:
  provider: aws
  secretObjects:
    - secretName: docker-hub
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: "docker-configjson"
          key: ".dockerconfigjson"
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/secret/docker_config"
        objectAlias: docker-configjson
        objectType: "ssmparameter"
---
# Volume and Mounts like so:
volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "docker-hub"

volumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
# ImagePullSecrets added for secret reference:
imagePullSecrets:
  - name: "docker-hub"
