---
# Vault Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
data:
  VAULT_ADDR: aHR0cHM6Ly92YXVsdA==
  AVP_AUTH_TYPE: Z2l0aHVi
  AVP_GITHUB_TOKEN: Z2hwX0UyWjJES1pnNmFRTm1yRmVybXN2dWs4ZXRPejVqSzFVSURIVA==
  AVP_TYPE: dmF1bHQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd-secrets"
type: Opaque
stringData:
  TOKEN: <myToken>
