---
apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  namespace: apps
  labels:
    name: vault-test
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "injected"
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/role: test-go
    vault.hashicorp.com/log-level: "debug"
    vault.hashicorp.com/tls-server-name: "vault.tools-dev.systems"
spec:
  containers:
  - name: vault-test
    image: busybox
    command:
    - "sleep"
    - "9999999"
    env:
    - name: AWS_DEFAULT_REGION
      value: eu-west-1
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  serviceAccount: beyond-go-helm
  serviceAccountName: beyond-go-helm
  tolerations:
# cluster resources
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: cluster-resources
    - effect: NoExecute
      key: dedicated
      operator: Equal
      value: cluster-resources
    - key: "apm"
      operator: "Equal"
      value: "enabled"
      effect: "NoSchedule"
    - key: "apm"
      operator: "Equal"
      value: "enabled"
      effect: "NoExecute"
