# https://github.com/aws-samples/eks-gitops-crossplane-argocd/blob/main/crossplane-complete/templates/5-aws-providerconfig.yaml
---
# ---
# apiVersion: aws.crossplane.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: default
#   annotations:
#     argocd.argoproj.io/sync-wave: "50"
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: aws-credentials
#       key: credentials

---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: InjectedIdentity
