# https://github.com/Yitaek/pomerium-iap-traefik/blob/master/cert-manager/wildcard-cert.yaml
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-cert
  dnsNames:
    - '*.mydomain.example.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
