# https://github.com/aws-samples/eks-gitops-crossplane-flux/blob/main/crossplane/crossplane-composite-resources.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-resources
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-configuration-package
  interval: 30s
  path: ./deploy/crossplane-xr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
